"""Shared configuration used by plotting entry points."""

CHANNEL_MAPPINGS = {
    "OC": {
        "rSLMActive": "SM",
        "aUndersteer_aSlip": "aUndersteerFromSlip",
    },
    "DIL": {
        "BSLMActiveCan": "SM",
        "FPushrodFL": "FPRodFL",
        "FPushrodFR": "FPRodFR",
        "FPushrodRL": "FPRodRL",
        "FPushrodRR": "FPRodRR",
        "EPlankWearLapF": "EPlankF",
        "PPlankWearF": "PPlankF",
        "pBrakeF1": "pBrakeF",
        "CAN_6_632_aSteerWheel_Can": "aSteerWheel",
    },
    "DLS": {
        "aRollCarTrack": "aRoll",
        "FPushrodFL": "FPRodFL",
        "FPushrodFR": "FPRodFR",
        "FPushrodRL": "FPRodRL",
        "FPushrodRR": "FPRodRR",
        "aUndersteer_aSlip": "aUndersteerFromSlip",
        "BAeroModeXDriver": "SM",
        "rThrottlePedal": "rThrottle",
        "EPlankLTS_Lap": "EPlankF",
        "PPlankWearF": "PPlankF",
    },
    "CAR": {
        "BNSLMEnablingStatusEnabled": "SM",
        "PMGUKActual": "PMGUK",
        "rThrottlePedal": "rThrottle",
        "xDamperPotFL": "xDamperFL",
        "xDamperPotFR": "xDamperFR",
        "xDamperPotRL": "xDamperRL",
        "xDamperPotRR": "xDamperRR",
        "nYawSlipSensor": "nYaw",
        "EPlankWearLapF": "EPlankF",
        "PPlankWearF": "PPlankF",
    },
}


UNITS_MAP = {
    "glat": "g",
    "glong": "g",
    "gvertf": "g",
    "gvertr": "g",
    "glat_abs": "g",
    "gLong (raw)": "g",
    "gVert": "g",
    "vcar": "kph",
    "aroll": "deg",
    "asteer": "deg",
    "asteerwheel": "deg",
    "aundersteerfromslip": "deg",
    "xrh": "mm",
    "laser": "mm",
    "hrider": "mm",
    "hridef": "mm",
    "damper": "mm",
    "xdamper": "mm",
    "fprod": "N",
    "fpushrod": "N",
    "pushrod": "N",
    "fprodfl": "N",
    "fprodfr": "N",
    "fprodrl": "N",
    "fprodrr": "N",
    "fprodavgf": "N",
    "fprodavgr": "N",
    "fproddeltaf": "N",
    "fproddeltar": "N",
    "trackrod": "N",
    "xdamperavgf": "mm",
    "xdamperavgr": "mm",
    "xdamperdeltaf": "mm",
    "xdamperdeltar": "mm",
    "nengine": "rpm",
    "mengine": "Nm",
    "msteerwheel": "Nm",
    "brake": "bar",
    "throttle": "%",
    "pmguk": "kW",
    "pengine": "kW",
    "nwheelr_avg": "rpm",
    "nyaw": "deg/s",
    "pbrakef": "bar",
    "rthrottle": "%",
    "EPlank_F": "kJ",
    "PPlank_F": "kW",
    "FzPlankF": "N",
    "dmInjector": "kg/h",
    "PMGUK_Deploy": "kW",
    "PMGUK_Charge": "kW",
    "dmInjector (kg/s)": "kg/s",
}
